version: '3.9'

services:

  ordersapiapppv012:
    container_name: web
    image: ${DOCKER_REGISTRY-}ordersapiapppv012
    ports: 
      - 5005:443
      - 8008:80
    build: 
      context: .
      dockerfile: OrdersApiAppPV012/Dockerfile
    depends_on:
      - db
    networks:
      - internal

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: OrderDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - internal

networks:
  internal:
    driver: bridge