version: '3.9'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "OrderDb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5433:5432"
